import type { EventDetail } from "@/types/events";

export const DEMO_EVENTS: EventDetail[] = [
  {
    id: "1",
    title: "Burgundy with Friends",
    slug: "burgundy-with-friends",
    event_type: "tasting",
    cover_image: "/images/event1.jpg",
    description: "An intimate guided tasting of premier cru Burgundy selections with our head sommelier.",
    long_description:
      "Join us for an evening dedicated to the great terroirs of Burgundy. Our head sommelier will guide you through six premier cru and grand cru selections from legendary domaines including Domaine Leroy, Domaine de la Romanée-Conti, and Domaine Leflaive.\n\nThe evening begins with a welcome glass of Crémant de Bourgogne, followed by a structured tasting exploring the nuances between villages, climats, and vintages. Each wine will be paired with artisanal cheeses from the same region.\n\nThis is an ideal gathering for those who appreciate the subtlety of Pinot Noir and Chardonnay at their finest. Spaces are intentionally limited to ensure every guest can engage deeply with both the wines and the conversation.",
    venue_name: "The Loft",
    venue_address: "42 Grove Street",
    venue_city: "West Village, NY",
    starts_at: "2026-06-15T19:00:00Z",
    ends_at: "2026-06-15T22:00:00Z",
    capacity: 24,
    rsvp_count: 18,
    is_featured: true,
    price_cents: 15000,
    host_id: null,
    gallery: [],
    tags: ["burgundy", "pinot noir", "premier cru"],
    min_plan_slug: null,
    required_capabilities: [],
  },
  {
    id: "2",
    title: "Sommelier's Table",
    slug: "sommeliers-table",
    event_type: "dinner",
    cover_image: "/images/event2.jpg",
    description: "A seven-course pairing dinner curated by our sommelier collective.",
    long_description:
      "The Sommelier's Table is our most coveted dining experience — a seven-course menu designed by Chef Antoine Mercier, with each course paired by a different member of our sommelier collective.\n\nFrom the amuse-bouche paired with a rare Jura Savagnin to the dessert course featuring a 30-year-old Tokaji Aszú, every moment is crafted to surprise and delight. The menu draws inspiration from the wines themselves, reversing the traditional pairing approach.\n\nSeating is at a single communal table, fostering conversation and connection among our most discerning members. Black tie optional, curiosity mandatory.",
    venue_name: "Maison Lumière",
    venue_address: "88 Leonard Street",
    venue_city: "Tribeca, NY",
    starts_at: "2026-06-22T20:00:00Z",
    ends_at: "2026-06-22T23:30:00Z",
    capacity: 12,
    rsvp_count: 10,
    is_featured: false,
    price_cents: 35000,
    host_id: null,
    gallery: [],
    tags: ["dinner", "pairing", "fine dining"],
    min_plan_slug: "connoisseur",
    required_capabilities: [],
  },
  {
    id: "3",
    title: "Tuscan Harvest Journey",
    slug: "tuscan-harvest",
    event_type: "journey",
    cover_image: "/images/event3.jpg",
    description: "A five-day immersion into Tuscan winemaking during the autumn harvest.",
    long_description:
      "Experience the magic of vendemmia in the heart of Tuscany. This five-day journey takes you through the rolling hills of Chianti Classico, Brunello di Montalcino, and Bolgheri during the most exciting time of the winemaking calendar.\n\nYou'll participate in the harvest alongside winemakers, visit underground cellars that date back centuries, and enjoy private dinners prepared by local chefs using ingredients sourced that morning.\n\nHighlights include a vertical tasting at Tenuta San Guido (Sassicaia), a sunrise hot-air balloon ride over the Val d'Orcia, and a private audience with a third-generation Brunello producer. Accommodation is at the historic Villa Marchetti, a restored 16th-century estate.",
    venue_name: "Villa Marchetti",
    venue_address: "Strada Provinciale",
    venue_city: "Tuscany, Italy",
    starts_at: "2026-09-10T10:00:00Z",
    ends_at: "2026-09-14T16:00:00Z",
    capacity: 16,
    rsvp_count: 8,
    is_featured: true,
    price_cents: 850000,
    host_id: null,
    gallery: [],
    tags: ["tuscany", "harvest", "travel", "italy"],
    min_plan_slug: "collector",
    required_capabilities: [],
  },
  {
    id: "4",
    title: "Champagne & Oysters",
    slug: "champagne-oysters",
    event_type: "experience",
    cover_image: "/images/event1.jpg",
    description: "An afternoon of grower Champagnes and East Coast oysters on the waterfront.",
    long_description:
      "There are few pairings more timeless than Champagne and oysters. This waterfront afternoon celebrates both with a curated selection of grower Champagnes — small-production gems from vignerons who farm, harvest, and bottle on their own estates.\n\nYou'll taste through six Champagnes ranging from Blanc de Blancs to vintage rosé, each paired with a different oyster variety sourced from the finest beds along the Eastern seaboard. Our oyster expert will guide you through the terroir of the sea while our sommelier connects it to the terroir of Champagne.\n\nThe event takes place on our private terrace overlooking the East River, with the Manhattan skyline as your backdrop.",
    venue_name: "The Pearl Room",
    venue_address: "1 Water Street",
    venue_city: "Brooklyn, NY",
    starts_at: "2026-07-04T18:00:00Z",
    ends_at: "2026-07-04T21:00:00Z",
    capacity: 20,
    rsvp_count: 14,
    is_featured: false,
    price_cents: 22500,
    host_id: null,
    gallery: [],
    tags: ["champagne", "oysters", "waterfront"],
    min_plan_slug: null,
    required_capabilities: [],
  },
  {
    id: "5",
    title: "Napa Valley Wine Trail",
    slug: "napa-valley-trail",
    event_type: "journey",
    cover_image: "/images/event2.jpg",
    description: "A weekend exploring Napa's most exclusive wineries with behind-the-scenes access.",
    long_description:
      "Discover the Napa Valley through a lens reserved for the most connected insiders. This weekend journey includes private library tastings, barrel room tours, and winemaker dinners at estates that rarely open their doors to visitors.\n\nDay one begins at a legendary Cabernet Sauvignon producer in the Stags Leap District, followed by lunch at a Michelin-starred restaurant in Yountville. The afternoon brings a visit to a cutting-edge biodynamic estate on Howell Mountain.\n\nDay two focuses on the cooler reaches of Carneros and the diverse terroirs of the Coombsville AVA, culminating in a farewell dinner at a private estate with panoramic valley views.",
    venue_name: "Multiple Wineries",
    venue_address: "Napa Valley",
    venue_city: "Napa Valley, CA",
    starts_at: "2026-08-15T09:00:00Z",
    ends_at: "2026-08-16T17:00:00Z",
    capacity: 12,
    rsvp_count: 4,
    is_featured: false,
    price_cents: 450000,
    host_id: null,
    gallery: [],
    tags: ["napa", "cabernet", "travel", "winery tour"],
    min_plan_slug: "connoisseur",
    required_capabilities: [],
  },
  {
    id: "6",
    title: "Blind Tasting Championship",
    slug: "blind-tasting",
    event_type: "tasting",
    cover_image: "/images/event3.jpg",
    description: "Test your palate against fellow members in our quarterly blind tasting competition.",
    long_description:
      "Think you can tell Bordeaux from Barolo? Our quarterly Blind Tasting Championship puts your palate to the ultimate test. Competitors are presented with eight wines served completely blind — no labels, no hints, no mercy.\n\nYou'll be scored on grape variety, region, vintage, and producer identification. The top three finishers earn loyalty points and bragging rights until the next championship. The reigning champion gets their name engraved on our perpetual trophy.\n\nWhether you're a seasoned competitor or a first-timer, the evening is as educational as it is entertaining. Our sommeliers reveal each wine after scoring, sharing the stories and techniques behind each selection. Light bites are served throughout.",
    venue_name: "The Wine Cellar",
    venue_address: "155 East 55th Street",
    venue_city: "Manhattan, NY",
    starts_at: "2026-07-20T19:30:00Z",
    ends_at: "2026-07-20T22:30:00Z",
    capacity: 30,
    rsvp_count: 22,
    is_featured: false,
    price_cents: 12500,
    host_id: null,
    gallery: [],
    tags: ["blind tasting", "competition", "education"],
    min_plan_slug: null,
    required_capabilities: [],
  },
];

export function getDemoEvent(slug: string): EventDetail | undefined {
  return DEMO_EVENTS.find((e) => e.slug === slug || e.id === slug);
}

export function getDemoRelatedEvents(currentSlug: string, limit = 3): EventDetail[] {
  return DEMO_EVENTS.filter((e) => e.slug !== currentSlug).slice(0, limit);
}
